### PR TITLE
Homework#2

### PR DESCRIPTION
**Pull request by enzomatela**
Cannot find juliuscnicolas, and kevinatgithub. baka pending invite pa kasi sila? hula lang po hehe

### CODE REVIEW

**Comment by jegtugado** [comment]
Hi sir. Please add the .gitignore file shared by sir Kevin on our Teams channel

**Comment by enzomatela** [comment]
nasa loob po ng masters.api yung gitignore

**Comment by jegtugado** [comment]
Current name is "gitignore" please change to ".gitignore"

**Comment by enzomatela** [comment]
done po

**Comment by jegtugado** [comment]
Since na create yung PR with wrong .gitignore file name hindi nag apply. Please follow the steps on https://stackoverflow.com/a/19757964/6138713 the accepted answer

**Review by jegtugado — APPROVED** [review]
Not sure why the other bin  files are still getting picked up but this is much better compared to before. Approved. The proctors will merge the PR once reviewed. You can create session 3 from session 2 branch for the next homework

**Pull request merged**
